import Separator from "./ui/Separator"

export default function Footer() {
  return (
    <footer
      className={`flex flex-col px-4 justify-center items-center gap-2 text-center pb-24 w-full font-mono relative z-10`}
      style={{
        background:
          "linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(33,33,33,1) 100%)",
      }}
    >
      <Separator />
      <h1 className="text-2xl pt-16 mt-8 pb-2 sm:text-4xl font-bold mx-auto">
        Hollywood Movies
      </h1>
      <h1 className="text-lg sm:text-xl font-bold mx-auto tracking-wider mx-auto -mt-2 mb-12">
        ~ generated by robots ~
      </h1>
      <div className="text-xl">
        Built by{" "}
        <a
          href="https://johnpolacek.com/"
          target="_blank"
          rel="noreferrer"
          className="font-bold hover:underline transition underline-offset-2 text-indigo-400"
        >
          John Polacek
        </a>
      </div>
      <div className="text-xl">
        You can follow me at{" "}
        <a
          href="https://twitter.com/johnpolacek"
          target="_blank"
          rel="noreferrer"
          className="font-bold hover:underline transition underline-offset-2 text-indigo-400"
        >
          @johnpolacek
        </a>
      </div>
      <div className="pt-4 text-xl">
        Inspired by the work of{" "}
        <a
          href="https://www.elmghari.com/"
          target="_blank"
          rel="noreferrer"
          className="font-bold hover:underline transition underline-offset-2 text-indigo-400"
        >
          Hassan El Mghari
        </a>{" "}
      </div>
      <div className="text-xl pt-4">
        Powered by{" "}
        <a
          href="https://openai.com/"
          target="_blank"
          rel="noreferrer"
          className="font-bold hover:underline transition underline-offset-2 text-indigo-400"
        >
          OpenAI{" "}
        </a>
      </div>
      <div className="text-xl">
        and{" "}
        <a
          href="https://vercel.com/"
          target="_blank"
          rel="noreferrer"
          className="font-bold hover:underline transition underline-offset-2 text-indigo-400"
        >
          Vercel Edge Functions.
        </a>
      </div>
    </footer>
  )
}
