import Image from "next/image"

export default function Header() {
  return (
    <header className="flex flex-col items-center w-full relative md:-mt-16">
      <h1 className="pt-4 md:pt-0 md:absolute top-20 text-2xl left-20 text-white z-20">
        <code style={{ textShadow: "0px 0px 6px rgba(255,255,255,1)" }}>
          botlywood.ca
        </code>
      </h1>
      <h1 className="pb-2 md:absolute top-20 mt-2 text-lg right-10 text-white z-20">
        <code style={{ textShadow: "0px 0px 2px rgba(0,0,0,1)" }}>
          hollywood movies generated by robots
        </code>
      </h1>
      <Image
        alt="header text"
        src="/botlywood.png"
        priority
        width={1728}
        height={864}
        className="w-full"
      />
      <div
        className="w-full h-3/4 absolute bottom-0 left-0 z-10"
        style={{
          background:
            "linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(0,0,0,1) 40%, rgba(0,0,0,0) 100%)",
        }}
      ></div>
    </header>
  )
}
