export default function Header() {
  return (
    <header className="flex flex-col items-center w-full relative md:-mt-16 2xl:sticky 2xl:top-0 2xl:left-0 z-40">
      <div
        className="cursor-pointer"
        onClick={() => {
          window.location.reload()
        }}
      >
        <h1 className="pt-4 md:pt-0 md:absolute top-20 2xl:top-8 text-2xl left-20 text-white z-20">
          <code style={{ textShadow: "0px 0px 6px rgba(255,255,255,1)" }}>
            botlywood.ca
          </code>
        </h1>
      </div>
      <h1 className="pb-4 md:pb-4 md:absolute top-20 2xl:top-8 mt-2 text-sm sm:text-lg 2xl:text-sm right-10 text-white z-20">
        <code style={{ textShadow: "0px 0px 2px rgba(0,0,0,1)" }}>
          hollywood movies generated by robots
        </code>
      </h1>
    </header>
  )
}
