import Document, { Head, Html, Main, NextScript } from "next/document"

const description = "botlywood.ca - hollywood movies generated by robots"
class MyDocument extends Document {
  render() {
    return (
      <Html lang="en">
        <Head>
          <link
            rel="icon"
            href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%2210 0 100 100%22><text y=%22.90em%22 font-size=%2290%22>🎥</text></svg>"
          />
          <meta name="description" content={description} />
          <meta property="og:site_name" content="botlywood.ca" />
          <meta property="og:description" content={description} />
          <meta property="og:title" content="botlywood.ca" />
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content="Twitter Bio Generator" />
          <meta name="twitter:description" content={description} />
          <meta
            property="og:image"
            content="https://botlywood.com/botlywood-screenshot.png"
          />
          <meta
            name="twitter:image"
            content="https://botlywood.com/botlywood-screenshot.png"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
