import type { NextPage } from "next"
import Head from "next/head"
import Header from "../components/Header"
import App from "../components/App"
import Footer from "../components/Footer"
import { AppContextProvider } from "../components/AppContext"

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-black text-white">
      <Head>
        <title>botlywood.ca - hollywood movies generated by robots</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <AppContextProvider>
        <App />
      </AppContextProvider>
      <Footer />
    </div>
  )
}

export default Home
